### ISSUE TITLE
Whats an use case for this?

### ISSUE THREAD

**Issue by andresaraujo** [brion25/jc-react-validate#1]
Do you think setting the same constraints for all the properties will be a common case ?

https://github.com/brion25/jc-react-validate/blob/b02f846476c33ced73103f56e941a24abc9da65f/src/helpers.js#L15

**Comment by brion25** [comment]
In case you want to appy the same constraint to multiple values, ex:

```
const options = {
  inspect: {
    on: 'state',
    attrs: ['fname', 'lname']
  },
  constraint: {
    presence: true
  }
}
```

that config will generate the following constraint:

```
{
  fname: {
    presence: true
  },
  lname: {
    presence: true
  }
}
```

**Comment by andresaraujo** [comment]
👍 Gotcha this is meant for simple/quick validation usage
